### PR TITLE
Multi level

### PR DESCRIPTION
**Pull request by yaakovLowenstein**

### CODE REVIEW

**Comment by yaakovLowenstein** [comment]
This solves the issue where a grandchild template
wants to render a block that does not exist in itself
or the parent template, but exists in the grandparent.

This builds on https://github.com/clokep/django-render-block/pull/45 but is simpler, I am unclear of all that was done in that PR. This PR solves the one issue outlined above.

Should solve https://github.com/clokep/django-render-block/issues/16 and https://github.com/clokep/django-render-block/issues/12

**Comment by clokep** [comment]
@yaakovLowenstein I think that #56 might fix this, but would be curious for more real world testing!

**Comment by yaakovLowenstein** [comment]
@clokep Just tested  https://github.com/clokep/django-render-block/pull/56t https://github.com/clokep/django-render-block/pull/56 and I believe it does solve the issue. Also from what I could tell it didn't look like anything broke

**Comment by clokep** [comment]
> @clokep Just tested #56 and I believe it does solve the issue. Also from what I could tell it didn't look like anything broke

Thank you! I think it works and makes the code much simpler, will probably need to do a beta release for it.

**Comment by yaakovLowenstein** [comment]
> > @clokep Just tested #56 and I believe it does solve the issue. Also from what I could tell it didn't look like anything broke
> 
> 
> 
> Thank you! I think it works and makes the code much simpler, will probably need to do a beta release for it.

Ok great! Looking forward. Thanks for updating it!

**Pull request closed without merging**
